[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
decorations = "None"
blur = true
startup_mode = "Maximized"

[terminal.shell]
program = "/bin/bash"
args = ["-l", "-c", "zellij"]

[font]
size = 14.0
offset = {x = 0, y = 2}

