[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
decorations = "None"
blur = true
startup_mode = "Maximized"

[terminal.shell]
program = "/bin/bash"
args = ["-l", "-c", "zellij"]

[font]
size = 14.0
offset = {x = 0, y = 2}

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
# family = "MonaspiceAr Nerd Font Mono Bold"
style = 'Bold'

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
# family = "MonaspiceAr Nerd Font Mono Bold Italic"
style = 'Bold Italic'

[font.italic]
# family = "MonaspiceAr Nerd Font Mono Italic"
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = 'Italic'

[font.normal]
# family = "MesloLGS Nerd Font Mono"
# family = "MonaspiceAr Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = 'Regular'
